version: '3.7'
services:
  node-explorer:
    image: kirito37/node-explorer:v0.1.0
    ports:
      - "3000:80"
    restart: always
    environment:
      - SERVER_PORT=30363
    depends_on:
      - node-server

  node-server:
    image: kirito37/node-server:v0.1.0
    expose:
      - 30363
    ports:
      - "30363:8580"
    restart: always
    volumes:
      - ${CORDAPPS_PATH}:/cordapps
